# Web Programming in Java

## H2 Database 
http://www.h2database.com/ 

### General Tips
* SQL conventions: https://www.sqlstyle.guide/
* H2 can be used in embedded mode or server mode; 
* user names are not case-sensitive, but passwords are; 
* SQL commands are not case-sensitive; 
* keywords are uppercase;
* names given by user are lowercase;
* fields of string type (`varchar`) have their values given between single quotation marks;
* dates must be given between single quotation marks and obey the format: `YYYY-mm-dd`; 
* for the current date, use `CURRENT_DATE`
* by default, H2 runs in autocommit mode, which means that when we modify a table, H2 stores the modifications permanently. If you need to disable this, uncheck the checkbox in the top left corner; 
* in the top right corner, the option `Auto Complete` is set as `Total`, which helps to construct the SQL commands. 
    
### Installation (for Linux)
      
1. Download the program from: http://www.h2database.com/html/main.html 
2. Extract to a folder; 
3. In a terminal, inside the folder `h2/bin`, enter `java -jar h2*.jar`
    
### Configuration and Creation of a Database in H2 (for Linux)
       
Configuration (in the browser):
* choose the desired language; 
* In `Active Configuration`, select: `Generic H2 (Server)`; 
* add the name of the database: `webprog`
* user and password: `admin` 
       
### Main commands to modify a database

1. Create a table: 
```sql
CREATE TABLE students (
             id      integer PRIMARY KEY AUTO_INCREMENT NOT NULL, 
             name    VARCHAR(255), 
             email   VARCHAR(255), 
             address VARCHAR(255)
); 
```

2. Insert a new record: 
```sql
INSERT INTO students (name, email, address) 
     VALUES ('Paul', 'paul@gmail.com', 'Rue Viau'); 
```
       
3. Update a record:
```sql
UPDATE students 
   SET name = 'Martine' 
 WHERE id = 1; 
```

4. Remove a record: 
```sql
DELETE FROM students 
      WHERE id = 1; 
```

5. Search for a record: 
```sql
SELECT name 
  FROM students 
 WHERE id = 2; 
```

6. List records: 
```sql
SELECT * 
  FROM students 
ORDER BY name;        
```